FROM golang:1.20 as gobuilder
WORKDIR /app
COPY go.mod go.sum ./
COPY apps/backend/cmd ./cmd
COPY apps/backend/pkg ./pkg
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=gobuilder /app/main .
EXPOSE 3000
CMD ["./main"]
